name: Hello-World
on: push
# Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello world!"
